package com.twill.news.app.constants;

import java.util.HashMap;

/**
 * Created by Anil on 6/7/2017.
 */

public class AppConstants {

    public static String APP_TAG = "twill";
    public static HashMap<String, String> NewsSourceLogo = new HashMap<>();

    static {
        NewsSourceLogo.put("abc-news", "https://icons.better-idea.org/icon?url=http://abcnews.go.com&size=70..120..200");
        NewsSourceLogo.put("abc-news-au", "https://icons.better-idea.org/icon?url=http://www.abc.net.au/news&size=70..120..200");
        NewsSourceLogo.put("aftenposten", "https://icons.better-idea.org/icon?url=https://www.aftenposten.no&size=70..120..200");
        NewsSourceLogo.put("al-jazeera-english", "https://icons.better-idea.org/icon?url=http://www.aljazeera.com&size=70..120..200");
        NewsSourceLogo.put("ansa", "https://icons.better-idea.org/icon?url=http://www.ansa.it&size=70..120..200");
        NewsSourceLogo.put("argaam", "https://icons.better-idea.org/icon?url=http://www.argaam.com&size=70..120..200");
        NewsSourceLogo.put("ars-technica", "https://icons.better-idea.org/icon?url=http://arstechnica.com&size=70..120..200");
        NewsSourceLogo.put("ary-news", "https://icons.better-idea.org/icon?url=https://arynews.tv/ud/&size=70..120..200");
        NewsSourceLogo.put("associated-press", "https://icons.better-idea.org/icon?url=https://apnews.com/&size=70..120..200");
        NewsSourceLogo.put("australian-financial-review", "https://icons.better-idea.org/icon?url=http://www.afr.com&size=70..120..200");
        NewsSourceLogo.put("axios", "https://icons.better-idea.org/icon?url=https://www.axios.com&size=70..120..200");
        NewsSourceLogo.put("bbc-news", "https://icons.better-idea.org/icon?url=http://www.bbc.co.uk/news&size=70..120..200");
        NewsSourceLogo.put("bbc-sport", "https://icons.better-idea.org/icon?url=http://www.bbc.co.uk/sport&size=70..120..200");
        NewsSourceLogo.put("bild", "https://icons.better-idea.org/icon?url=http://www.bild.de&size=70..120..200");
        NewsSourceLogo.put("blasting-news-br", "https://icons.better-idea.org/icon?url=http://br.blastingnews.com&size=70..120..200");
        NewsSourceLogo.put("bleacher-report", "https://icons.better-idea.org/icon?url=http://www.bleacherreport.com&size=70..120..200");
        NewsSourceLogo.put("bloomberg", "https://icons.better-idea.org/icon?url=http://www.bloomberg.com&size=70..120..200");
        NewsSourceLogo.put("breitbart-news", "https://icons.better-idea.org/icon?url=http://www.breitbart.com&size=70..120..200");
        NewsSourceLogo.put("business-insider", "https://icons.better-idea.org/icon?url=http://www.businessinsider.com&size=70..120..200");
        NewsSourceLogo.put("business-insider-uk", "https://icons.better-idea.org/icon?url=http://uk.businessinsider.com&size=70..120..200");
        NewsSourceLogo.put("buzzfeed", "https://icons.better-idea.org/icon?url=https://www.buzzfeed.com&size=70..120..200");
        NewsSourceLogo.put("cbc-news", "https://icons.better-idea.org/icon?url=http://www.cbc.ca/news&size=70..120..200");
        NewsSourceLogo.put("cbs-news", "https://icons.better-idea.org/icon?url=http://www.cbsnews.com&size=70..120..200");
        NewsSourceLogo.put("cnbc", "https://icons.better-idea.org/icon?url=http://www.cnbc.com&size=70..120..200");
        NewsSourceLogo.put("cnn", "https://icons.better-idea.org/icon?url=http://us.cnn.com&size=70..120..200");
        NewsSourceLogo.put("cnn-es", "https://icons.better-idea.org/icon?url=http://cnnespanol.cnn.com/&size=70..120..200");
        NewsSourceLogo.put("crypto-coins-news", "https://icons.better-idea.org/icon?url=https://www.cryptocoinsnews.com&size=70..120..200");
        NewsSourceLogo.put("daily-mail", "https://icons.better-idea.org/icon?url=http://www.dailymail.co.uk/home/index.html&size=70..120..200");
        NewsSourceLogo.put("der-tagesspiegel", "https://icons.better-idea.org/icon?url=http://www.tagesspiegel.de&size=70..120..200");
        NewsSourceLogo.put("die-zeit", "https://icons.better-idea.org/icon?url=http://www.zeit.de/index&size=70..120..200");
        NewsSourceLogo.put("el-mundo", "https://icons.better-idea.org/icon?url=http://www.elmundo.es&size=70..120..200");
        NewsSourceLogo.put("engadget", "https://icons.better-idea.org/icon?url=https://www.engadget.com&size=70..120..200");
        NewsSourceLogo.put("entertainment-weekly", "https://icons.better-idea.org/icon?url=http://www.ew.com&size=70..120..200");
        NewsSourceLogo.put("espn", "https://icons.better-idea.org/icon?url=http://espn.go.com&size=70..120..200");
        NewsSourceLogo.put("espn-cric-info", "https://icons.better-idea.org/icon?url=http://www.espncricinfo.com/&size=70..120..200");
        NewsSourceLogo.put("financial-post", "https://icons.better-idea.org/icon?url=http://business.financialpost.com&size=70..120..200");
        NewsSourceLogo.put("financial-times", "https://icons.better-idea.org/icon?url=http://www.ft.com/home/uk&size=70..120..200");
        NewsSourceLogo.put("focus", "https://icons.better-idea.org/icon?url=http://www.focus.de&size=70..120..200");
        NewsSourceLogo.put("football-italia", "https://icons.better-idea.org/icon?url=http://www.football-italia.net&size=70..120..200");
        NewsSourceLogo.put("fortune", "https://icons.better-idea.org/icon?url=http://fortune.com&size=70..120..200");
        NewsSourceLogo.put("four-four-two", "https://icons.better-idea.org/icon?url=http://www.fourfourtwo.com/news&size=70..120..200");
        NewsSourceLogo.put("fox-news", "https://icons.better-idea.org/icon?url=http://www.foxnews.com&size=70..120..200");
        NewsSourceLogo.put("fox-sports", "https://icons.better-idea.org/icon?url=http://www.foxsports.com&size=70..120..200");
        NewsSourceLogo.put("globo", "https://icons.better-idea.org/icon?url=http://www.globo.com/&size=70..120..20");
        NewsSourceLogo.put("google-news", "https://icons.better-idea.org/icon?url=https://news.google.com&size=70..120..200");
        NewsSourceLogo.put("google-news-ar", "https://icons.better-idea.org/icon?url=https://news.google.com&size=70..120..200");
        NewsSourceLogo.put("google-news-au", "https://icons.better-idea.org/icon?url=https://news.google.com&size=70..120..200");
        NewsSourceLogo.put("google-news-br", "https://icons.better-idea.org/icon?url=https://news.google.com&size=70..120..200");
        NewsSourceLogo.put("google-news-ca", "https://icons.better-idea.org/icon?url=https://news.google.com&size=70..120..200");
        NewsSourceLogo.put("google-news-fr", "https://icons.better-idea.org/icon?url=https://news.google.com&size=70..120..200");
        NewsSourceLogo.put("google-news-in", "https://icons.better-idea.org/icon?url=https://news.google.com&size=70..120..200");
        NewsSourceLogo.put("google-news-is", "https://icons.better-idea.org/icon?url=https://news.google.com&size=70..120..200");
        NewsSourceLogo.put("google-news-it", "https://icons.better-idea.org/icon?url=https://news.google.com&size=70..120..200");
        NewsSourceLogo.put("google-news-ru", "https://icons.better-idea.org/icon?url=https://news.google.com&size=70..120..200");
        NewsSourceLogo.put("google-news-sa", "https://icons.better-idea.org/icon?url=https://news.google.com&size=70..120..200");
        NewsSourceLogo.put("google-news-uk", "https://icons.better-idea.org/icon?url=https://news.google.com&size=70..120..200");
        NewsSourceLogo.put("goteborgs-posten", "https://icons.better-idea.org/icon?url=http://www.gp.se&size=70..120..200");
        NewsSourceLogo.put("gruenderszene", "https://icons.better-idea.org/icon?url=http://www.gruenderszene.de&size=70..120..200");
        NewsSourceLogo.put("hacker-news", "https://icons.better-idea.org/icon?url=https://news.ycombinator.com&size=70..120..200");
        NewsSourceLogo.put("handelsblatt", "https://icons.better-idea.org/icon?url=http://www.handelsblatt.com&size=70..120..200");
        NewsSourceLogo.put("ign", "https://icons.better-idea.org/icon?url=http://www.ign.com&size=70..120..200");
        NewsSourceLogo.put("il-sole-24-ore", "https://icons.better-idea.org/icon?url=http://www.ilsole24ore.com&size=70..120..200");
        NewsSourceLogo.put("independent", "https://icons.better-idea.org/icon?url=http://www.independent.co.uk&size=70..120..200");
        NewsSourceLogo.put("infobae", "https://icons.better-idea.org/icon?url=http://www.infobae.com/?noredirect&size=70..120..200");
        NewsSourceLogo.put("info-money", "https://icons.better-idea.org/icon?url=http://www.infomoney.com.br&size=70..120..200");
        NewsSourceLogo.put("la-gaceta", "https://icons.better-idea.org/icon?url=http://www.lagaceta.com.ar&size=70..120..200");
        NewsSourceLogo.put("la-nacion", "https://icons.better-idea.org/icon?url=http://www.lanacion.com.ar&size=70..120..200");
        NewsSourceLogo.put("la-repubblica", "https://icons.better-idea.org/icon?url=http://www.repubblica.it&size=70..120..200");
        NewsSourceLogo.put("le-monde", "https://icons.better-idea.org/icon?url=http://www.lemonde.fr&size=70..120..200");
        NewsSourceLogo.put("lenta", "https://icons.better-idea.org/icon?url=https://lenta.ru&size=70..120..200");
        NewsSourceLogo.put("lequipe", "https://icons.better-idea.org/icon?url=https://www.lequipe.fr&size=70..120..200");
        NewsSourceLogo.put("les-echos", "https://icons.better-idea.org/icon?url=https://www.lesechos.fr&size=70..120..200");
        NewsSourceLogo.put("liberation", "https://icons.better-idea.org/icon?url=http://www.liberation.fr&size=70..120..200");
        NewsSourceLogo.put("marca", "https://icons.better-idea.org/icon?url=http://www.marca.com&size=70..120..200");
        NewsSourceLogo.put("mashable", "https://icons.better-idea.org/icon?url=http://mashable.com&size=70..120..200");
        NewsSourceLogo.put("medical-news-today", "https://icons.better-idea.org/icon?url=http://www.medicalnewstoday.com&size=70..120..200");
        NewsSourceLogo.put("metro", "https://icons.better-idea.org/icon?url=http://metro.co.uk&size=70..120..200");
        NewsSourceLogo.put("mirror", "https://icons.better-idea.org/icon?url=http://www.mirror.co.uk/&size=70..120..200");
        NewsSourceLogo.put("msnbc", "https://icons.better-idea.org/icon?url=http://www.msnbc.com&size=70..120..200");
        NewsSourceLogo.put("mtv-news", "https://icons.better-idea.org/icon?url=http://www.mtv.com/news&size=70..120..200");
        NewsSourceLogo.put("mtv-news-uk", "https://icons.better-idea.org/icon?url=http://www.mtv.co.uk/news&size=70..120..200");
        NewsSourceLogo.put("national-geographic", "https://icons.better-idea.org/icon?url=http://news.nationalgeographic.com&size=70..120..200");
        NewsSourceLogo.put("nbc-news", "https://icons.better-idea.org/icon?url=http://www.nbcnews.com&size=70..120..200");
        NewsSourceLogo.put("news24", "https://icons.better-idea.org/icon?url=http://www.news24.com&size=70..120..200");
        NewsSourceLogo.put("new-scientist", "https://icons.better-idea.org/icon?url=https://www.newscientist.com/section/news&size=70..120..200");
        NewsSourceLogo.put("news-com-au", "https://icons.better-idea.org/icon?url=http://www.news.com.au&size=70..120..200");
        NewsSourceLogo.put("newsweek", "https://icons.better-idea.org/icon?url=http://www.newsweek.com&size=70..120..200");
        NewsSourceLogo.put("new-york-magazine", "https://icons.better-idea.org/icon?url=http://nymag.com&size=70..120..200");
        NewsSourceLogo.put("next-big-future", "https://icons.better-idea.org/icon?url=https://www.nextbigfuture.com&size=70..120..200");
        NewsSourceLogo.put("nfl-news", "https://icons.better-idea.org/icon?url=http://www.nfl.com/news&size=70..120..200");
        NewsSourceLogo.put("nhl-news", "https://icons.better-idea.org/icon?url=https://www.nhl.com/news&size=70..120..200");
        NewsSourceLogo.put("nrk", "https://icons.better-idea.org/icon?url=https://www.nrk.no&size=70..120..200");
        NewsSourceLogo.put("politico", "https://icons.better-idea.org/icon?url=https://www.politico.com&size=70..120..200");
        NewsSourceLogo.put("polygon", "https://icons.better-idea.org/icon?url=http://www.polygon.com&size=70..120..200");
        NewsSourceLogo.put("rbc", "https://icons.better-idea.org/icon?url=http://www.rbc.ru&size=70..120..200");
        NewsSourceLogo.put("recode", "https://icons.better-idea.org/icon?url=http://www.recode.net&size=70..120..200");
        NewsSourceLogo.put("reddit-r-all", "https://icons.better-idea.org/icon?url=https://www.reddit.com/r/all&size=70..120..200");
        NewsSourceLogo.put("reuters", "https://icons.better-idea.org/icon?url=http://www.reuters.com&size=70..120..200");
        NewsSourceLogo.put("rt", "https://icons.better-idea.org/icon?url=https://russian.rt.com&size=70..120..200");
        NewsSourceLogo.put("rte", "https://icons.better-idea.org/icon?url=https://www.rte.ie/news&size=70..120..200");
        NewsSourceLogo.put("rtl-nieuws", "https://icons.better-idea.org/icon?url=https://www.rtlnieuws.nl/&size=70..120..200");
        NewsSourceLogo.put("sabq", "https://icons.better-idea.org/icon?url=https://sabq.org&size=70..120..200");
        NewsSourceLogo.put("spiegel-online", "https://icons.better-idea.org/icon?url=http://www.spiegel.de&size=70..120..200");
        NewsSourceLogo.put("svenska-dagbladet", "https://icons.better-idea.org/icon?url=https://www.svd.se&size=70..120..200");
        NewsSourceLogo.put("t3n", "https://icons.better-idea.org/icon?url=http://t3n.de&size=70..120..200");
        NewsSourceLogo.put("talksport", "https://icons.better-idea.org/icon?url=http://talksport.com&size=70..120..200");
        NewsSourceLogo.put("techcrunch", "https://icons.better-idea.org/icon?url=https://techcrunch.com&size=70..120..200");
        NewsSourceLogo.put("techcrunch-cn", "https://icons.better-idea.org/icon?url=https://techcrunch.cn&size=70..120..200");
        NewsSourceLogo.put("techradar", "https://icons.better-idea.org/icon?url=http://www.techradar.com&size=70..120..200");
        NewsSourceLogo.put("the-economist", "https://icons.better-idea.org/icon?url=http://www.economist.com&size=70..120..200");
        NewsSourceLogo.put("the-globe-and-mail", "https://icons.better-idea.org/icon?url=https://www.theglobeandmail.com&size=70..120..200");
        NewsSourceLogo.put("the-guardian-au", "https://icons.better-idea.org/icon?url=https://www.theguardian.com/au&size=70..120..200");
        NewsSourceLogo.put("the-guardian-uk", "https://icons.better-idea.org/icon?url=https://www.theguardian.com/uk&size=70..120..200");
        NewsSourceLogo.put("the-hill", "https://icons.better-idea.org/icon?url=http://thehill.com&size=70..120..200");
        NewsSourceLogo.put("the-hindu", "https://icons.better-idea.org/icon?url=http://www.thehindu.com&size=70..120..200");
        NewsSourceLogo.put("the-huffington-post", "https://icons.better-idea.org/icon?url=http://www.huffingtonpost.com&size=70..120..200");
        NewsSourceLogo.put("the-irish-times", "https://icons.better-idea.org/icon?url=https://www.irishtimes.com&size=70..120..200");
        NewsSourceLogo.put("the-lad-bible", "https://icons.better-idea.org/icon?url=http://www.theladbible.com&size=70..120..200");
        NewsSourceLogo.put("the-new-york-times", "https://icons.better-idea.org/icon?url=http://www.nytimes.com&size=70..120..200");
        NewsSourceLogo.put("the-next-web", "https://icons.better-idea.org/icon?url=http://thenextweb.com&size=70..120..200");
        NewsSourceLogo.put("the-sport-bible", "https://icons.better-idea.org/icon?url=http://www.thesportbible.com&size=70..120..200");
        NewsSourceLogo.put("the-telegraph", "https://icons.better-idea.org/icon?url=http://www.telegraph.co.uk&size=70..120..200");
        NewsSourceLogo.put("the-times-of-india", "https://icons.better-idea.org/icon?url=http://timesofindia.indiatimes.com&size=70..120..200");
        NewsSourceLogo.put("the-verge", "https://icons.better-idea.org/icon?url=http://www.theverge.com&size=70..120..200");
        NewsSourceLogo.put("the-wall-street-journal", "https://icons.better-idea.org/icon?url=http://www.wsj.com&size=70..120..200");
        NewsSourceLogo.put("the-washington-post", "https://icons.better-idea.org/icon?url=https://www.washingtonpost.com&size=70..120..200");
        NewsSourceLogo.put("time", "https://icons.better-idea.org/icon?url=http://time.com&size=70..120..200");
        NewsSourceLogo.put("usa-today", "https://icons.better-idea.org/icon?url=http://www.usatoday.com/news&size=70..120..200");
        NewsSourceLogo.put("vice-news", "https://icons.better-idea.org/icon?url=https://news.vice.com&size=70..120..200");
        NewsSourceLogo.put("wired", "https://icons.better-idea.org/icon?url=https://www.wired.com&size=70..120..200");
        NewsSourceLogo.put("wired-de", "https://icons.better-idea.org/icon?url=https://www.wired.de&size=70..120..200");
        NewsSourceLogo.put("wirtschafts-woche", "https://icons.better-idea.org/icon?url=http://www.wiwo.de&size=70..120..200");
        NewsSourceLogo.put("xinhua-net", "https://icons.better-idea.org/icon?url=http://xinhuanet.com/&size=70..120..200");
        NewsSourceLogo.put("ynet", "https://icons.better-idea.org/icon?url=http://www.ynet.co.il&size=70..120..200");

     /*   NewsSourceLogo.put("associated-press", "https://pbs.twimg.com/profile_images/461964160838803457/8z9FImcv.png");
        NewsSourceLogo.put("bbc-news", "http://m.files.bbci.co.uk/modules/bbc-morph-news-waf-page-meta/1.2.0/apple-touch-icon.png");
        NewsSourceLogo.put("bbc-sport", "http://static.bbci.co.uk/onesport/2.11.72/images/web-icons/bbc-sport-144.png");
        NewsSourceLogo.put("bild", "http://bilder.bild.de/fotos/bild-de-35605834/Bild/3.bild.png");
        NewsSourceLogo.put("bloomberg", "https://assets.bwbx.io/business/public/images/favicons/apple-touch-icon-120x120-ef3226f2bd.png");
        NewsSourceLogo.put("breitbart-news", "http://www.breitbart.com/apple-touch-icon-152x152.png");
        NewsSourceLogo.put("business-insider", "http://uk.businessinsider.com/apple-touch-icon-precomposed.png?r=US&IR=T");
        NewsSourceLogo.put("business-insider-uk", "http://uk.businessinsider.com/apple-touch-icon-precomposed.png?r=US&IR=T");
        NewsSourceLogo.put("buzzfeed", "https://www.buzzfeed.com/static-assets/img/touch-icon-ios_120.208a0e329cd6e8d831b21ae17fb6aabb.png");
        NewsSourceLogo.put("cnbc", "https://pbs.twimg.com/profile_images/700355164734156800/1k4mmfUm.png");
        NewsSourceLogo.put("cnn", "http://i.cdn.cnn.com/cnn/.e/img/3.0/global/misc/apple-touch-icon.png");
        NewsSourceLogo.put("der-tagesspiegel", "http://www.tagesspiegel.de/images/apple-touch-icon/9800138/2-formatOriginal.png");
        NewsSourceLogo.put("die-zeit", "http://img.zeit.de/static/img/ZO-ipad-114x114.png");
        NewsSourceLogo.put("daily-mail", "http://www.dailymail.co.uk/apple-touch-icon.png");
        NewsSourceLogo.put("engadget", "https://s.blogsmithmedia.com/www.engadget.com/assets-h542c367293ab884b565544d560f51a1d/images/apple-touch-icon-120x120.png?h=232a14b1a350de05a49b584a62abac9e");
        NewsSourceLogo.put("entertainment-weekly", "http://1.gravatar.com/blavatar/782bdf163168ca78e52d32d27b830793?s=114");
        NewsSourceLogo.put("espn", "http://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espn_icon-152x152.min.png");
        NewsSourceLogo.put("espn-cric-info", "https://pbs.twimg.com/profile_images/436105065598689281/Fm7w2M89.png");
        NewsSourceLogo.put("financial-times", "https://www.ft.com/__assets/creatives/brand-ft/icons/v2/apple-touch-icon-180x180.png");
        NewsSourceLogo.put("football-italia", "https://pbs.twimg.com/profile_images/2514923001/kvc336eae86bjgy8ys1s.jpeg");
        NewsSourceLogo.put("fortune", "http://1.gravatar.com/blavatar/dab01945b542bffb69b4f700d7a35f8f?s=114");
        NewsSourceLogo.put("four-four-two", "https://images.cdn.fourfourtwo.com/sites/fourfourtwo.com/themes/fourfourtwo/images/apple-icon-144x144px.png");
        NewsSourceLogo.put("google-news", "https://ssl.gstatic.com/news-static/img/1703439073-news-thumb-128_w.png");
        NewsSourceLogo.put("gruenderszene","https://www.gruenderszene.de/images/apple/apple-touch-icon-120x120.png");
        NewsSourceLogo.put("hacker-news", "https://pbs.twimg.com/profile_images/723571201449295877/-KeG1OdO.jpg");
        NewsSourceLogo.put("handelsblatt", "http://www.handelsblatt.com/images/apple-touch-icon/3896854/2-formatOriginal.png");
        NewsSourceLogo.put("ign", "http://m.ign.com/apple-touch-icon-precomposed.png");
        NewsSourceLogo.put("independent", "http://www.independent.co.uk/sites/all/themes/ines_themes/independent_theme/img/apple-icon-120x120.png");
        NewsSourceLogo.put("mashable", "http://mashable.com/apple-touch-icon-120x120.png?v=m2Pmw8zNwl");
        NewsSourceLogo.put("metro", "http://1.gravatar.com/blavatar/72ba1fb4e57339685f67d1d89b3db216?s=120");
        NewsSourceLogo.put("mirror", "https://pbs.twimg.com/profile_images/798143742205186048/PpRgSwh0.jpg");
        NewsSourceLogo.put("mtv-news", "http://www.mtv.com/apple-touch-icon-precomposed.png");
        NewsSourceLogo.put("mtv-news-uk", "https://pbs.twimg.com/profile_images/1801520411/MTV_News_Logo_Black.png");
        NewsSourceLogo.put("national-geographic", "https://pbs.twimg.com/profile_images/798181194202566656/U8QbCBdH.jpg");
        NewsSourceLogo.put("new-scientist", "https://pbs.twimg.com/profile_images/843789564074496001/m34mTHmg_400x400.jpg");
        NewsSourceLogo.put("newsweek", "https://icons.better-idea.org/icon?url=http://www.newsweek.com&size=70..120..200");
        NewsSourceLogo.put("new-york-magazine", "http://cache.nymag.com/media/nymag/icon.120x120.png");
        NewsSourceLogo.put("nfl-news", "http://i.nflcdn.com/static/site/7.5/img/apple/apple-touch-icon-114x114.png?7.5hotfix/7.5.11");
        NewsSourceLogo.put("polygon", "https://cdn2.vox-cdn.com/uploads/hub/sbnu_logo_minimal/405/touch_icon_ipad_retina_1000x1000.7014.png");
        NewsSourceLogo.put("recode", "https://cdn1.vox-cdn.com/uploads/chorus_asset/file/6397047/recode_favicon-180.0.png");
        NewsSourceLogo.put("reddit-r-all", "https://www.redditstatic.com/mweb2x/favicon/120x120.png");
        NewsSourceLogo.put("reuters", "http://s1.reutersmedia.net/resources_v3/images/favicon/apple-touch-icon-120x120.png");
        NewsSourceLogo.put("talksport", "https://pbs.twimg.com/profile_images/2263073636/profilepic_400x400.jpg");
        NewsSourceLogo.put("techcrunch", "https://s0.wp.com/wp-content/themes/vip/techcrunch-2013/assets/images/homescreen_TCIcon_ipad_2x.png");
        NewsSourceLogo.put("techradar", "http://cdn0.static.techradar.futurecdn.net/20170609/apple-touch-icon.png");
        NewsSourceLogo.put("the-economist", "https://pbs.twimg.com/profile_images/461499742950678528/2JnpHjUo.png");
        NewsSourceLogo.put("the-guardian-au", "https://assets.guim.co.uk/images/favicons/cf23080600002e50f5869c72f5a904bd/120x120.png");
        NewsSourceLogo.put("the-guardian-uk", "https://assets.guim.co.uk/images/favicons/cf23080600002e50f5869c72f5a904bd/120x120.png");
        NewsSourceLogo.put("the-hindu", "https://pbs.twimg.com/profile_images/627376030282416128/pYl_LmcW_400x400.jpg");
        NewsSourceLogo.put("the-huffington-post", "https://pbs.twimg.com/profile_images/856721681368457216/Ea5fWaGp.jpg");
        NewsSourceLogo.put("fox-sports", "https://pbs.twimg.com/profile_images/824007776489738241/pFk_8LLO.jpg");
        NewsSourceLogo.put("the-lad-bible", "http://bilder.bild.de/fotos/bild-de-35605834/Bild/3.bild.png");
        NewsSourceLogo.put("the-new-york-times", "https://mobile.nytimes.com/vi-assets/apple-touch-icon-319373aaf4524d94d38aa599c56b8655.png");
        NewsSourceLogo.put("the-sport-bible", "http://www.sportbible.com/assets/images/theme/favicons/apple-touch-icon-120x120.png");
        NewsSourceLogo.put("the-telegraph", "https://pbs.twimg.com/profile_images/704631788019314688/D20twdRX.jpg");
        NewsSourceLogo.put("the-times-of-india", "https://pbs.twimg.com/profile_images/781514680732749824/PG2_gebm.jpg");
        NewsSourceLogo.put("the-verge", "https://cdn2.vox-cdn.com/uploads/chorus_asset/file/7395359/ios-icon.0.png");
        NewsSourceLogo.put("the-wall-street-journal", "https://www.wsj.com/apple-touch-icon-precomposed.png");
        NewsSourceLogo.put("the-washington-post", "https://pbs.twimg.com/profile_images/753656134565785600/iQ1GX-ov.jpg");
        NewsSourceLogo.put("time", "http://s0.wp.com/wp-content/themes/vip/time2014/img/time-touch_icon_120.png");
        NewsSourceLogo.put("usa-today", "https://www.gannett-cdn.com/mobile-web/usat-mobile/v1/images/native-ios-114.png");
        NewsSourceLogo.put("wirtschafts-woche","https://pbs.twimg.com/profile_images/596378323128836096/23C3DVmy.jpg");
        NewsSourceLogo.put("focus","http://p5.focus.de/favicon_120.png");
        NewsSourceLogo.put("the-next-web","https://cdn2.tnwcdn.com/wp-content/themes/cyberdelia/assets/icons/apple-touch-icon-120x120.png?v=1495618267");
        NewsSourceLogo.put("wired-de","https://pbs.twimg.com/profile_images/719888833211404288/oICq1CSu.jpg");*/
    }

        public static class API_CONSTANTS {
            public static final String NEWS_API_BASE_URL = "https://newsapi.org";
            public static final String GRAPHY_API_BASE_URL = "http://api.giphy.com";
            public static final String NEWS_API_KEY = "9d9d719c8a534afba2bf4c054ee87fb4";
            public static final String GRAPHY_API_KEY = "dc6zaTOxFJmzC";
            public static final String CONTENT_TYPE_APPLICATION_JSON = "Content-Type: application/json;";
            public static final String REQUEST_NEWS_SOURCES = "/v1/sources";
            public static final String REQUEST_NEWS_ARTICLES = "/v1/articles";
            public static final int TIMEOUT_IN_SEC = 15;
        }
    }
